import { describe, expect, test } from '@jest/globals'
import { v4 } from './v4'

describe('v4 function', () => {
  test('check the validity of the UUID generated by v4', () => {
    const uuid = v4()

    // Regex pattern of our uuid
    const uuidPattern = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$/

    // check if the pattern returned is valid
    const isValidUUID = uuidPattern.test(uuid!)

    expect(isValidUUID).toBe(true)
  })

  test('check the uniqueness of UUIDs generated by v4', () => {
    const numberOfUUIDs = 1000 // generating 1000 of uuids to test
    const generatedUUIDs = new Set()

    // Generate UUIDs and add them to a Set to check for uniqueness
    for (let i = 0; i < numberOfUUIDs; i++) {
      const uuid = v4()
      generatedUUIDs.add(uuid)
    }

    // If all UUIDs are unique, the Set size should be equal to the number of generated UUIDs
    expect(generatedUUIDs.size).toBe(numberOfUUIDs)
  })
})
